### ISSUE TITLE
Fedora 34: `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by ngaywood** [nxadm/rakudo-pkg#85]
[root]# rpm -q rakudo-pkg                    
rakudo-pkg-2021.6.0-01.x86_64

[root]# /opt/rakudo-pkg/bin/raku
/opt/rakudo-pkg/bin/raku: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /opt/rakudo-pkg/bin/raku)
/opt/rakudo-pkg/bin/raku: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /opt/rakudo-pkg/bin/../lib/libmoar.so)

[root]# dnf downgrade rakudo-pkg
[snip]

[root]# rpm -q rakudo-pkg
rakudo-pkg-2021.5.0-01.x86_64

[root]# /opt/rakudo-pkg/bin/raku
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.05.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.05.

**Comment by ngaywood** [comment]
This is an odd problem. 
rakudo-pkg-2021.6.0-01.x86_64 works fine on two of my Fedora 34 systems.
Fails with the GLIBC not found message on 3 other Fedora 34 systems.

**Comment by ngaywood** [comment]
OK, found why some installations worked and some did not.

In the ones that worked I installed the /etc/yum.repos.d/nxadm-pkgs-rakudo-pkg.repo file when the system was Fedora 33
The Fedora version number is hard coded:
   baseurl=https://dl.cloudsmith.io/public/nxadm-pkgs/rakudo-pkg/rpm/fedora/33/$basearch

After updating the system to Fedora 34, I was still installing the Fedora 33 raku packages.

The Fedora 34 systems I installed later had:
   baseurl=https://dl.cloudsmith.io/public/nxadm-pkgs/rakudo-pkg/rpm/fedora/34/$basearch

and when I try to run packages installed here I get:

$ raku
raku: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by raku)
raku: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /opt/rakudo-pkg/bin/../lib/libmoar.so)

**Comment by nxadm** [comment]
Thx for the issue. Weird indeed. I am investigating it.

**Comment by nxadm** [comment]
OK, pushed a new revision for Fedora 34. It was a mix-up because Rawhide moved from 34 to 35 when Fedora 34 was released:
cloudsmith push rpm nxadm-pkgs/rakudo-pkg/fedora/34 rakudo-pkg-Fedora34-2021.06-02.x86_64.rpm

Checking rpm package upload parameters ... OK
Checking rakudo-pkg-Fedora34-2021.06-02.x86_64.rpm file upload parameters ... OK
Requesting file upload for rakudo-pkg-Fedora34-2021.06-02.x86_64.rpm ... OK
Creating a new rpm package ... OK
Created: nxadm-pkgs/rakudo-pkg/rakudo-pkg-fedora34-202106-02x86_64rpm-9oW (4brqqTsPBDOb)


Package synchronised successfully in 11.480673 second(s)!
