### ISSUE TITLE
path problems

### ISSUE THREAD

**Issue by ToddAndMargo** [nxadm/rakudo-pkg#9]
Scientific Linux 7.3 (RHEL clone), x64

After removing EPEL's rakudo and installing

https://github.com/nxadm/rakudo-pkg/releases/download/2017.03_02/perl6-rakudo-moarvm-CentOS7.3.1611-20170300-02.x86_64.rpm 

I had a bit of a panic on my hands.  All on my p6 code starts with 
#!/usr/bin/perl6
, which is the expected location.  And you do not install at that location.

The following is missing from your scripts and documentation (from my notes):

Then update your path:
    # vi /etc/profile
      under the last pathmunge, add (depending on where perl6 really is)
           # perl 6's panda path
           # pathmunge /usr/share/perl6/site/bin after
           pathmunge /opt/rakudo/bin after

And make a link from the actual location to the expected location
    # ln -s /opt/rakudo/bin/perl6  /usr/bin/perl6

Many thanks,
-T

**Comment by nxadm** [comment]
Thank you, T.

I see what you mean about the default location for the perl6 binary. However, the packages here are meant to compliment and not to replace the perl6 packages supplied by the system (e.g. used by other applications). 

It's pretty common for dynamic languages to use the the binary in your PATH instead of hardcoding a location. The shebang for that is:
`#!/usr/bin/env perl6`

This is also standard practice for perl 5, python and ruby. This way you can decide for each application what binary you use to run the script.

Regards,
C.
